// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9WE_0dLU80p3zozADU62uT5IsUuquoxM',
    appId: '1:126241171499:web:4c129086ba24c9deab626e',
    messagingSenderId: '126241171499',
    projectId: 'cariinv2',
    authDomain: 'cariinv2.firebaseapp.com',
    storageBucket: 'cariinv2.appspot.com',
    measurementId: 'G-PXF7DP3KX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6OMZliOvRXqUqkTikWgsyEjYQqiRkp-A',
    appId: '1:126241171499:android:52bde6a3e8c81b0bab626e',
    messagingSenderId: '126241171499',
    projectId: 'cariinv2',
    storageBucket: 'cariinv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDd65f1Twb6Ey2xZu8X5VcxSqaAZEhvaw',
    appId: '1:126241171499:ios:5ffa8cc9f28a2f4fab626e',
    messagingSenderId: '126241171499',
    projectId: 'cariinv2',
    storageBucket: 'cariinv2.appspot.com',
    iosClientId: '126241171499-dvc28cmb1fi6n8kaqu8a4aa5fgljs6cn.apps.googleusercontent.com',
    iosBundleId: 'com.example.cariinV2',
  );
}
